import { List } from "./list";
import { Order } from "./order";
import { LexPosition, Position } from "./position";
import { LexUtils } from "./util/lex_utils";

/**
 * A local (non-collaborative) data structure mapping [[Position]]s to
 * values, in list order.
 *
 * You can use a LocalList to maintain a sorted, indexable view of a
 * [[CValueList]], [[CList]], or [[CText]]'s values.
 * For example, when using a [[CList]],
 * you could store its archived values in a LocalList.
 * That would let you iterate over the archived values in list order.
 *
 * To construct a LocalList that uses an existing list's positions, pass
 * that list's `totalOrder` to our constructor.
 *
 * It is *not* safe to modify a LocalList while iterating over it. The iterator
 * will attempt to throw an exception if it detects such modification,
 * but this is not guaranteed.
 *
 * @typeParam T The value type.
 */
export class LexList<T> {
  readonly order: Order;
  readonly list: List<T>;

  /**
   * Constructs a LocalList whose allowed [[Position]]s are given by
   * `source`.
   *
   * Using positions that were not generated by `source` (or a replica of
   * `source`) will cause undefined behavior.
   *
   * @param order The source for positions that may be used with this
   * LocalList.
   */
  constructor(order?: Order) {
    this.list = new List(order);
    this.order = this.list.order;
  }

  /**
   * Use with save()'d state. (Rename vars to savedState?)
   */
  static from<T>(
    lexPosMap: { [lexPos: LexPosition]: T },
    order?: Order
  ): LexList<T> {
    const lexList = new LexList<T>(order);
    lexList.load(lexPosMap);
    return lexList;
  }

  // ----------
  // Mutators
  // ----------

  /**
   * Sets the value at `pos`.
   *
   * @throws TODO pos invalid
   */
  set(lexPos: LexPosition, value: T): void {
    this.list.set(this.order.unlex(lexPos), value);
  }

  /**
   * Sets the value at index.
   *
   * @throws If index is not in `[0, this.length)`.
   */
  setAt(index: number, value: T): void {
    this.list.setAt(index, value);
  }

  /**
   * Deletes the given position, making it no longer
   * present in this list.
   *
   * @returns Whether the position was actually deleted, i.e.,
   * it was initially present.
   */
  delete(lexPos: LexPosition): void {
    this.list.delete(this.order.unlex(lexPos));
  }

  /**
   * Deletes the value at index.
   *
   * @throws If index is not in `[0, this.length)`.
   */
  deleteAt(index: number): void {
    this.list.deleteAt(index);
  }

  /**
   * Deletes every value in the list.
   *
   * The Order is unaffected (retains all Nodes).
   */
  clear() {
    this.list.clear();
  }

  /**
   *
   * @param prevPos
   * @param values
   * @returns { first value's new position, createdNodeDesc if created by Order }.
   * If values.length > 1, their positions start at pos using the same Node
   * with increasing valueIndex.
   * If values.length = 0, a new position is created but the List state is not
   * changed - can use this instead of calling Order.createPosition directly.
   * @throws If prevPos is order.maxPosition.
   */
  insert(prevLexPos: LexPosition, ...values: T[]): LexPosition[] {
    const { startPos } = this.list.insert(
      this.order.unlex(prevLexPos),
      ...values
    );
    return this.lexAll(startPos, values.length);
  }

  /**
   *
   * @param index
   * @param values
   * @returns
   * @throws If index is this.length and our last value is at order.maxPosition.
   */
  insertAt(index: number, ...values: T[]): LexPosition[] {
    const { startPos } = this.list.insertAt(index, ...values);
    return this.lexAll(startPos, values.length);
  }

  private lexAll(startPos: Position, count: number): LexPosition[] {
    // Use nodeSummary as opt over calling order.lex on each Position.
    const nodeSummary = this.order.summary(this.order.getNodeFor(startPos));
    const lexPositions = new Array<LexPosition>(count);
    for (let i = 0; i < count; i++) {
      lexPositions[i] = LexUtils.fromSummary(
        nodeSummary,
        startPos.valueIndex + i
      );
    }
    return lexPositions;
  }

  // ----------
  // Accessors
  // ----------

  /**
   * Returns the value at position, or undefined if it is not currently present
   * ([[hasPosition]] returns false).
   */
  get(lexPos: LexPosition): T | undefined {
    return this.list.get(this.order.unlex(lexPos));
  }

  /**
   * Returns the value currently at index.
   *
   * @throws If index is not in `[0, this.length)`.
   * Note that this differs from an ordinary Array,
   * which would instead return undefined.
   */
  getAt(index: number): T {
    return this.list.getAt(index);
  }

  /**
   * Returns whether position is currently present in the list,
   * i.e., its value is present.
   */
  has(lexPos: LexPosition): boolean {
    return this.list.has(this.order.unlex(lexPos));
  }

  /**
   * Returns the current index of position.
   *
   * If position is not currently present in the list
   * ([[hasPosition]] returns false), then the result depends on searchDir:
   * - "none" (default): Returns -1.
   * - "left": Returns the next index to the left of position.
   * If there are no values to the left of position,
   * returns -1.
   * - "right": Returns the next index to the right of position.
   * If there are no values to the right of position,
   * returns [[length]].
   *
   * To find the index where a position would be if
   * present, use `searchDir = "right"`.
   */
  indexOfPosition(
    lexPos: LexPosition,
    searchDir: "none" | "left" | "right" = "none"
  ): number {
    return this.list.indexOfPosition(this.order.unlex(lexPos), searchDir);
  }

  /**
   * Returns the position currently at index.
   *
   * Won't return minPosition or maxPosition. TODO: actually, will if they're
   * part of the list - check that code is compatible.
   */
  positionAt(index: number): LexPosition {
    return this.order.lex(this.list.positionAt(index));
  }

  /**
   * The length of the list.
   */
  get length() {
    return this.list.length;
  }

  // ----------
  // Iterators
  // ----------

  /** Returns an iterator for values in the list, in list order. */
  [Symbol.iterator](): IterableIterator<T> {
    return this.values();
  }

  /**
   * Returns an iterator for values in the list, in list order.
   *
   * Args as in Array.slice.
   */
  values(start?: number, end?: number): IterableIterator<T> {
    return this.list.values(start, end);
  }

  /**
   * Returns a copy of a section of this list, as an array.
   *
   * Args as in Array.slice.
   */
  slice(start?: number, end?: number): T[] {
    return this.list.slice(start, end);
  }

  /**
   * Returns an iterator for present positions, in list order.
   *
   * Args as in Array.slice.
   */
  *lexPositions(start?: number, end?: number): IterableIterator<LexPosition> {
    for (const pos of this.list.positions(start, end))
      yield this.order.lex(pos);
  }

  /**
   * Returns an iterator of [pos, value, index] tuples for every
   * value in the list, in list order.
   *
   * Args as in Array.slice.
   */
  *entries(
    start?: number,
    end?: number
  ): IterableIterator<[lexPos: LexPosition, value: T, index: number]> {
    for (const [pos, value, index] of this.list.entries(start, end)) {
      yield [this.order.lex(pos), value, index];
    }
  }

  // ----------
  // Save & Load
  // ----------

  /**
   * Returns saved state describing the current state of this LocalList,
   * including its values.
   *
   * The saved state may later be passed to [[load]]
   * on a new instance of LocalList, to reconstruct the
   * same list state.
   *
   * Only saves values, not Order. "Natural" format; order
   * guarantees (list order).
   */
  save(): { [lexPos: LexPosition]: T } {
    const lexPosMap: { [lexPos: LexPosition]: T } = {};
    for (const [lexPos, value] of this.entries()) lexPosMap[lexPos] = value;
    return lexPosMap;
  }

  /**
   * Loads saved state. The saved state must be from
   * a call to [[save]] on a LocalList whose `source`
   * constructor argument was a replica of this's
   * `source`, so that we can understand the
   * saved state's Positions.
   *
   * Overwrites whole state - not state-based merge.
   *
   * @param savedState Saved state from a List's
   * [[save]] call.
   */
  load(lexPosMap: { [lexPos: LexPosition]: T }): void {
    // TODO
  }
}
